apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-aad-postgres-hosted-elasticsearch
  namespace: open-liberty-demo
spec:
  replicas: 1
  # NOTE:
  # - replace "${CONTAINER_REGISTRY}" with your valid container registry name
  # - use format "docker.io/${Your_DockerHub_Account}" if Docker Hub is used as your container repositories
  applicationImage: ${CONTAINER_REGISTRY}/open-liberty-demo:1.0.0
  serviceAccountName: filebeat-svc-account
  expose: true
  service:
    port: 9443
    certificateSecretRef: tls-crt-secret
  route:
    termination: reencrypt
    certificateSecretRef: tls-crt-secret
  env:
  - name: KEY_ALIAS
    value: 'defaultkeystore'
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: client.id
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: client.secret
  - name: TENANT_ID
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: tenant.id
  - name: ADMIN_GROUP_ID
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: admin.group.id  
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.password
  - name: WLP_LOGGING_MESSAGE_FORMAT
    value: JSON
  - name: WLP_LOGGING_MESSAGE_SOURCE
    value: message,trace,accessLog,ffdc,audit
  volumeMounts:
  - name: logs-volume
    mountPath: /logs
  volumes:
  - name: logs-volume
    emptyDir: {}
  - name: config
    configMap:
      defaultMode: 0600
      name: filebeat-config
  sidecarContainers:
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.6.2
    args: [
      "-c", "/etc/filebeat.yml",
      "-e",
    ]
    securityContext:
      runAsUser: 0
      privileged: true
    env:
    - name: ELASTIC_CLOUD_ID
      valueFrom:
        secretKeyRef:
          name: elastic-cloud-secret
          key: elastic.cloud.id
    - name: ELASTIC_CLOUD_AUTH
      valueFrom:
        secretKeyRef:
          name: elastic-cloud-secret
          key: elastic.cloud.auth
    volumeMounts:
    - name: config
      mountPath: /etc/filebeat.yml
      readOnly: true
      subPath: filebeat.yml
    - name: logs-volume
      mountPath: /logs
      readOnly: true

