apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-aad-postgres-cluster-logging
  namespace: open-liberty-demo
spec:
  replicas: 1
  # NOTE:
  # - replace "${CONTAINER_REGISTRY}" with your valid container registry name
  # - use format "docker.io/${Your_DockerHub_Account}" if Docker Hub is used as your container repositories
  applicationImage: ${CONTAINER_REGISTRY}/open-liberty-demo:1.0.0
  expose: true
  service:
    port: 9443
    certificateSecretRef: tls-crt-secret
  route:
    termination: reencrypt
    certificateSecretRef: tls-crt-secret
  env:
  - name: KEY_ALIAS
    value: 'defaultkeystore'
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: client.id
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: client.secret
  - name: TENANT_ID
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: tenant.id
  - name: ADMIN_GROUP_ID
    valueFrom:
      secretKeyRef:
        name: aad-oidc-secret
        key: admin.group.id  
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.password
